version: '3.8'

# Development override - simpler setup without building Docker images

services:
  redis:
    image: redis:7-alpine
    container_name: dreamquest-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  redis_dev_data:
