name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
          vercel-args: '--prod'

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render/Railway
        run: |
          echo "Backend deployment to Render/Railway"
          echo "Configure this with your deployment service"
          # Example for Railway:
          # curl -X POST https://api.railway.app/deploy \
          #   -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          #   -d '{"service": "api"}'
